name: Check HTML for Dummy Text

on:
  push:
    branches:
      - main
    paths:
      - "**/*.html"
      - "**/*.php"

jobs:
  check-dummy-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Check for dummy text in HTML files
        run: npm run check-dummy-text
